on:
  push:
    tags:
      - 'v*'
name: Release new version
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: go get
        run: go get -u -v ./...
      - name: goreleaser
        uses: docker://goreleaser/goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: release
        if: success()